# Build settings
permalink   : /blog/:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

source: source
destination: ../site
sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO settings
title: Genvega, AWS Cloud Automation
description: "Genvega, inc. is a AWS partner and solutions architecture company."
keywords: "AWS, Cloud, Scalability, Availability, Performance, IT"
url: http://www.genvega.com
baseurl: ""
# baseurl: ""

# google_analytics: UA-52446115-1
repo: http://github.com/genvega/genvega.github.io
disqus_shortname: "genvega"

# Author settings
author:
  name      : Sachin Dole
  job       : AWS Solutions Architect
  bio       : "Genvega"
  thumb     : /images/LogoColorNoText120WideBorder.png
  email     : sdole@genvega.com
  url       : http://www.genvega.com
  github    : http://github.com/sdole
  twitter   : http://twitter.com/sdoledotcom
  facebook  : http://facebook.com/fernando.dev
  linkedin  : http://www.linkedin.com/in/sdole

# navbar pages
navbar:
  # - slug: about
  #  title: About
  # - slug: resume
  #   title: Resume
  # - slug: skills
  #   title: Skills
  # - slug: blog
  #  title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]